### ISSUE TITLE
Cannot read properties of undefined (reading 'verifyString')

### ISSUE THREAD

**Issue by kartikkalia74** [Mateo-tem/discord-modals#108]
when using modal throwing this error also discord modal is initilised with discord client

Documents/work/bot-backend/node_modules/discord-modals/src/structures/Modal.js:74
    this.customId = Util.verifyString(customId, RangeError, 'MODAL_CUSTOM_ID');
                         ^
TypeError: Cannot read properties of undefined (reading 'verifyString')
    at Modal.setCustomId (/Users//Documents/work/bot-backend/node_modules/discord-modals/src/structures/Modal.js:74:26)
    at Client.<anonymous> (/Users/Documents/work/bot-backend/src/services/discord/initial.ts:145:9)
    at Client.emit (node:events:527:28)

**Comment by Mikael** [comment]
getting this as well

**Comment by steodec** [comment]
Same

**Comment by Landelin** [comment]
Same here

**Comment by MaximeBeasse** [comment]
This seems to be a problem with how the Util module of discord.js is being exported.
At the time of the latest discord-modals version, discord.js exported its Util modal using this line :
`exports.Util = require('./util/Util');`

Now, since a few commits, it exports it that way :
`__exportStar(require('./util/Util.js'), exports);`

Discord-Modals still requires this module with this instruction:
`const { Util } = require('discord.js');`
So it needs to be changed to
`const { verifyString} = require('discord.js');`
and remove all the occurences of `Util`.

A quicker fix would be to downgrade to discord.js@13.9.2

**Comment by Mateo-tem** [comment]
I hope that today that issue can be resolved. I identified the problem about 3 weeks ago and It's solved, but I need to publish the version with other fixes, which will probably be today.

**Comment by Mateo-tem** [comment]
Discord-Modals v1.3.8 was released! Hope this problem is solved.

**Comment by MaximeBeasse** [comment]
It all works now with v1.3.9, thanks!
Keep up the good work!
