### ISSUE TITLE
discord modals error

### ISSUE THREAD

**Issue by tekashix0** [Mateo-tem/discord-modals#13]
Hello guys, I have a problem with this module, I write the command and the bot just stays as "Kinoshi is thinking..." and does not take any action, please help.

![error](https://cdn.discordapp.com/attachments/944993522849841183/947468970540298290/unknown.png)
![console](https://cdn.discordapp.com/attachments/913430212375629845/947468853854761031/unknown.png)

**Comment by Mateo-tem** [comment]
Show me your code please.

**Comment by Mateo-tem** [comment]
**First of all, thanks to report your issue!**

That problem is because you deferred the Interaction, the Interaction is like 'Acknowledged', and 
it does not allow to show the modal. Both of them (`deferReply()` and `showModal()`), manage the Interaction. If one function uses the interaction, another can no longer use it unless they have certain similarities and can collaborate to handle the interaction, like `deferReply()` and `followUp()`. If you delete `deferReply()` probably that will be resolved.
