### ISSUE TITLE
Feature Request: implement modal.update

### ISSUE THREAD

**Issue by lumap** [Mateo-tem/discord-modals#35]
You can use interaction.update({content: "helo", components: []}) with discord.js's buttons to edit the original message, but this function does not seem to exist for the modal argument in client.on('modalSubmit',...). Will it be implemented one day?

**Comment by Mateo-tem** [comment]
**Oh yes!** I have tested and it works! Will be implemented in the next version, which will be published today.

`ModalSubmitInteraction.update()` will work if the interaction was invoked on a Button or a Select Menu because they have a message. If there is not a message, will throw an error.

**Thanks!**
