### ISSUE TITLE
"undefined" instead of "null" in User and GuildMember.user classes in Modal class

### ISSUE THREAD

**Issue by Gesugao-san** [Mateo-tem/discord-modals#66]
![image](https://user-images.githubusercontent.com/28023014/162615085-2713a2b8-2c8d-4364-9df4-17af4ecb757f.png)

![image](https://user-images.githubusercontent.com/28023014/162615155-1f4c14e0-07a1-4ba5-b495-4e338c30c334.png)

---
P.S. Not critical for me, just notice it.
P.S.S. Thank you very much, mr. @Mateo-tem, for this package.

**Comment by Mateo-tem** [comment]
**Thanks for reporting this issue!**

Ohh, well I checked and this is not a discord-modals problem, the origin of this issue is from discord.js. the Users Manager of discord.js doesn't use null instead of undefined, I test different interactions of discord.js and it's the same.

![image](https://user-images.githubusercontent.com/79017590/162832563-fd1dcc7b-b8d6-4cac-9df0-8ad5e5b09b88.png)
